INSERT INTO guindastes (
    id,
    cliente,
    altura_torre,
    operacao,
    equipamento,
    configuracao,
    comprimento_lanca,
    comprimento_luffing_jib,
    contrapeso,
    contrapeso_ballast,
    cs_12m_atv,
    cs_14m_atv,
    p4_12m_atv,
    p4_14m_atv,
    p4_12m_dolly_atv,
    equipamento_auxiliar_atv,
    cs_12m_gdt,
    cs_14m_gdt,
    p4_12m_gdt,
    p4_14m_gdt,
    equipamento_auxiliar_mtg,
    cs_12m_mtg,
    created_at,
    updated_at,
    p4_12m_dolly_gdt,
    observacoes
  )
VALUES (
    'id:bigint',
    'cliente:character varying',
    'altura_torre:character varying',
    'operacao:character varying',
    'equipamento:character varying',
    'configuracao:character varying',
    'comprimento_lanca:character varying',
    'comprimento_luffing_jib:character varying',
    'contrapeso:character varying',
    'contrapeso_ballast:character varying',
    'cs_12m_atv:character varying',
    'cs_14m_atv:character varying',
    'p4_12m_atv:character varying',
    'p4_14m_atv:character varying',
    'p4_12m_dolly_atv:character varying',
    'equipamento_auxiliar_atv:character varying',
    'cs_12m_gdt:character varying',
    'cs_14m_gdt:character varying',
    'p4_12m_gdt:character varying',
    'p4_14m_gdt:character varying',
    'equipamento_auxiliar_mtg:character varying',
    'cs_12m_mtg:character varying',
    'created_at:timestamp without time zone',
    'updated_at:timestamp without time zone',
    'p4_12m_dolly_gdt:character varying',
    'observacoes:text'
  );